rimov/urls.py
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path('', include('rimov.core.urls', namespace='core')),
    path('crm/', include('rimov.crm.urls', namespace='crm')),
    path('imovel/', include('rimov.imovel.urls', namespace='imovel')),
    path('usuario/', include('rimov.usuario.urls', namespace='usuario')),
    path('media/<path>/', serve, {'document_root = settings.MEDIA_ROOT'}),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rimov/usuario/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from rimov.usuario import views as v
from rimov.usuario.forms import LoginForm


app_name = 'usuario'


urlpatterns = [
    path('', v.FuncionarioListView.as_view(), name='funcionario_list'),
    path('login/', LoginView.as_view(form_class=LoginForm), name='login'),
    path(
        'logout/',
        LogoutView.as_view(),
        # {'next_page': settings.LOGOUT_REDIRECT_URL},
        name='logout'
    ),
    path('add/', v.funcionario_create, name='funcionario_create'),
    path('<int:id>/', v.funcionario_detail, name='funcionario_detail'),
    path('<int:pk>/update/', v.FuncionarioUpdateView.as_view(), name='funcionario_update'),
    path('<int:pk>/delete/', v.FuncionarioDeleteView.as_view(), name='funcionario_delete'),
]

rimov/usuario/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse_lazy
from .constants import TIPOS_USUARIOS


class Funcionario(models.Model):
    usuario = models.OneToOneField(User, verbose_name='usuário', on_delete=models.CASCADE)
    tipo = models.CharField(
        'tipo de funcionário',
        max_length=15,
        choices=TIPOS_USUARIOS,
        default='CORRETOR',
        help_text='Campos obrigatórios'
    )
    avatar = models.ImageField(
        default='media/media/avatar.jpg',
        upload_to='media/',
        blank=True,
        null=True
    )
    cri = models.CharField('registro CRI', max_length=100, blank=True, null=True)
    telefone = models.CharField('telefone', max_length=100, blank=True, null=True)
    instagram = models.CharField('perfil Instagram', max_length=400, blank=True, null=True)
    facebook = models.CharField('perfil Facebook', max_length=400, blank=True, null=True)

    class Meta:
        ordering = ('usuario__first_name',)
        verbose_name = 'funcionário'
        verbose_name_plural = 'funcionários'

    def __str__(self):
        if self.usuario.get_full_name():
            return self.usuario.get_full_name()
        return self.usuario.email

    def get_absolute_url(self):
        return reverse_lazy('usuario:funcionario_update', args=[str(self.pk)])

    def get_delete_url(self):
        return reverse_lazy('usuario:funcionario_delete', args=[str(self.pk)])

rimov/usuario/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from .constants import TIPOS_USUARIOS


class LoginForm(AuthenticationForm):
    username = forms.EmailField(label='E-mail')

    class Meta:
        model = User


class UserAdminCreationForm(UserCreationForm):
    ''' Cadastro geral de Usuário. '''
    first_name = forms.CharField(label='Nome')
    last_name = forms.CharField(label='Sobrenome')
    email = forms.EmailField(label='E-mail')
    tipo = forms.ChoiceField(
        label='Tipo de funcionário',
        choices=TIPOS_USUARIOS,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    avatar = forms.FileField(required=False)
    cri = forms.CharField(label='CRI', required=False)
    telefone = forms.CharField(label='Telefone', required=False)
    instagram = forms.CharField(label='Instagram', required=False)
    facebook = forms.CharField(label='Facebook', required=False)

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
            'tipo',
            'avatar',
            'cri',
            'telefone',
            'instagram',
            'facebook',
        )

    def save(self, commit=True):
        instance = super(UserAdminCreationForm, self).save(commit=False)
        # Salva username = email
        instance.username = self.cleaned_data['email']
        if commit:
            instance.save()
        return instance

rimov/usuario/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import UpdateView, DeleteView
from .models import Funcionario
from .forms import UserAdminCreationForm


class FuncionarioListView(ListView):
    model = Funcionario


def funcionario_create(request):
    form = UserAdminCreationForm(request.POST or None)
    template_name = 'usuario/funcionario_form.html'

    if form.is_valid():
        # Pega email para filtrar User.
        email = form.cleaned_data['email']
        user = User.objects.filter(email=email).first()
        if user:
            msg = 'Email já cadastro. Favor fazer login.'
            messages.error(request, msg)
            return redirect(reverse_lazy('usuario:login'))
        else:
            user = form.save()
            # Cria Funcionario
            funcionario, _ = Funcionario.objects.get_or_create(
                usuario=user,
                tipo=form.cleaned_data['tipo'],
                avatar=form.cleaned_data['avatar'],
                cri=form.cleaned_data['cri'],
                telefone=form.cleaned_data['telefone'],
                instagram=form.cleaned_data['instagram'],
                facebook=form.cleaned_data['facebook'],
            )
        return redirect(reverse_lazy('usuario:funcionario_list'))
    return render(request, template_name, {'form': form})

def funcionario_detail(request, id):
    funcionario = get_object_or_404(Funcionario, pk=id)
    return render(request, 'usuario/funcionario_detail.html', {'funcionario': funcionario})



class FuncionarioUpdateView(UpdateView):
    model = Funcionario
    fields = '__all__'
    success_url = 'usuario:funcionario_list'

    def get_success_url(self):
        msg = 'Dados do usuário atualizados com sucesso.'
        messages.success(self.request, msg)
        return reverse(self.success_url)


class FuncionarioDeleteView(DeleteView):
    model = Funcionario
    success_url = 'usuario:funcionario_list'

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL. If the object is protected, send an error message.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        try:
            self.object.delete()
        except Exception as e:
            messages.error(request, 'Há dependências ligadas a esse usuário, permissão negada.')
        return redirect(self.success_url)

rimov/usuario/templates/usuario/funcionario_confirm_delete.html
{% extends 'base.html' %}
{% block title %}
Confirmação de exclusão
{% endblock %}
{% block content %}
<form method="post">
  {% csrf_token %}
  Você tem certeza que quer excluir o funcionário <b>{{ funcionario.nome }}</b>? <br><br>
  <button type="button" style="margin-left: 300px">
    <a href="{% url 'usuario:funcionario_list' %}">Cancelar</a>
  </button>
  <button>Excluir</button>
</form>
{% endblock %}

rimov/usuario/templates/usuario/funcionario_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="row">
  <div class="col-lg-8">
    <div class="card">
      <div class="card-header">
        {{ funcionario.nome }}        
        <a class="pull-right btn btn-sm btn-primary mr-2" style="color: white" href="{% url 'usuario:funcionario_update' funcionario.pk %}">
          <i class="fa fa-edit"></i> Editar
        </a>
        <span class="badge badge-success pull-right mr-2">Ativo</span>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-6">
            <img src="{{ funcionario.avatar.url }}" width="200px">
          </div>
          <div class="col-6">
            <h4><small><span class="text-muted">Tipo:</span></small>
              {{ funcionario.get_tipo_display }}
            </h4>
            <h4><small><span class="text-muted">Nome:</span></small>
              {{ funcionario.usuario.get_full_name }}
            </h4>
            <h4><small><span class="text-muted">CRI:</span></small>
              {{ funcionario.cri }}
            </h4>
            <h4><small><span class="text-muted">Telefone:</span></small>
              {{ funcionario.telefone }}
            </h4>
            <h4><small><span class="text-muted">Email:</span></small>
              {{ funcionario.usuario }}
            </h4>
          </div>
        </div>
      </div>
      <ul class="list-group list-group-flush">
        
        <li class="list-group-item">
          <h4 align="center">Redes Sociais</h4>
          <ul class="list-group list-group-flush">
            <li class="list-group-item no-border"><span class="text-muted">Facebook:</span>{{ funcionario.facebook }}</li>
            <li class="list-group-item no-border"><span class="text-muted">Instagram:</span>{{ funcionario.instagram }}</li> 
          </ul>
        </li>
       <!--<li class="list-group-item">
          <h4>Observation</h4>
          <p class="text-justify">Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, ex, corrupti! Assumenda, distinctio quasi magnam delectus qui et illum reiciendis ea consequuntur mollitia? Mollitia in enim labore consectetur nostrum corrupti.</p>
        </li>-->
      </ul>
    </div>
  </div>
  <!-- <div class="col-lg-3">
    <div class="card">
      <div class="card-header">
        Contacts
        <span class="pull-right badge badge-success i-is-link" data-toggle="modal" data-target="#mymodal"><i class="fa fa-plus"></i> Add</span>
      </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item no-border">
            <span class="badge badge-warning">type</span> 11 98765-4321
            <span class="span-is-link pull-right" data-toggle="modal" data-target="#mymodal">
              <i class="fa fa-edit" style="margin-left: 10px;"></i>
            </span>
          </li>
        </ul>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        Title
        <span class="pull-right badge badge-success i-is-link" data-toggle="modal" data-target="#mymodal"><i class="fa fa-plus"></i> Add</span>
      </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <ul class="list-group list-group-flush">
              <li class="list-group-item no-border li-line pl-0 pr-0">
                <span class="text-muted">Label:</span> <span class="lead">text</span>
                <span class="span-is-link float-right" data-toggle="modal" data-target="#mymodal">
                  <i class="fa fa-edit" style="margin-left: 10px;"></i>
                </span>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div> -->
  <!--<div class="col-lg-3">
    <div class="card">
      <div class="card-header">
        Corretor
        <span class="pull-right badge badge-success i-is-link" data-toggle="modal" data-target="#mymodal"><i class="fa fa-plus"></i> Adicionar</span>
      </div>
      <div>
         card-body 
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <ul class="list-group list-group-flush">
              <li class="list-group-item no-border li-line pl-0 pr-0">
                <span class="lead">{{ funcionario. }}</span>
                <span class="span-is-link pull-right" data-toggle="modal" data-target="#mymodal">
                  <i class="fa fa-edit" style="margin-left: 10px;"></i>
                </span>
              </li>
              <li class="list-group-item no-border li-line pl-0 pr-0"><span class="text-muted"></span> {{ funcionario.telefone }}</li>
               <li class="list-group-item no-border li-line pl-0 pr-0"><span class="text-muted">Label:</span> text</li>
              <li class="list-group-item no-border li-line pl-0 pr-0"><span class="text-muted">Label:</span> text</li>
              <li class="list-group-item no-border li-line pl-0 pr-0"><span class="text-muted">Label:</span>
                <span class="badge badge-success">Yes</span>
              </li>
              <li class="list-group-item li-line pl-0 pr-0">
                <span class="text-muted">Observation:</span>
                <p class="text-justify">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda tenetur alias cupiditate dicta blanditiis facilis rerum animi at unde, fugit. Aliquid quos, id illo autem praesentium. Amet reprehenderit rerum, veritatis.</p>
              </li> 
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>-->
</div>
<!-- Modal -->
{% include "includes/modal.html" %}
{% endblock content %}

rimov/usuario/templates/usuario/funcionario_form.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block css %}
<style type="text/css">
input[type=text] {
  text-transform: uppercase;
}

span.required:after {
  content: "*";
  color: red;
}
</style>
{% endblock css %}
{% block content %}
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header">
        <strong>Cadastro de Funcionários</strong>
        <!-- <small>Form</small> -->
      </div>
      <div class="card-body">
        <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error {% endif %}">
            <label for="{{ field.id_for_label }}">
              {% if field.field.required %}
              <span class="required">{{ field.label }} </span>
              {% else %}
              {{ field.label }}
              {% endif %}
            </label>
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
            <span class="text-muted">{{ error }}</span>
            {% endfor %}
          </div>
          {% endfor %}
          <input type="button" value="Voltar" class="btn btn-info" onClick="history.go(-1)"> <input type="submit" class="btn btn-success" value="Salvar">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block js %}
<script>
  $(document).ready(function() {
    $('#id_telefone').mask('(00) 00000-0000');
    $('input[name=avatar]').removeClass('form-control');
  });
</script>
{% endblock js %}

rimov/usuario/templates/usuario/funcionario_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Imóveis
        <span class="float-right">1 of 10 resultados (100 total)</span>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-md-auto">
            <a class="btn btn-primary" href="{% url 'usuario:funcionario_create' %}">
              <i class="fa fa-plus"></i>
              Adicionar
            </a>
          </div>
          <div class="col">
            <form action="." method="GET">
              <div class="row">
                <div class="col p-ari-5">
                  <input name="search" class="form-control mb-2" type="text" placeholder="Busca..." />
                </div>
                <div class="col-auto">
                  <button class="btn btn-success mb-2" type="submit">OK</button>
                  <button class="btn btn-link mb-2">Limpar</button>
                </div>
              </div>
            </form>
          </div>
        </div>
        <!-- TABLE -->
        <table class="table table-responsive-sm table-hover table-striped">
          <thead>
            <tr>
              <th>ID</th>
                <th>NOME</th>
                <th>TELEFONE</th>
                <th>CRI</th>
                <th>FOTO</th>
                <th>EMAIL</th>
                <th>TIPO</th>
                <th>AÇÃO</th>
            </tr>
          </thead>
          <tbody>
            {% for funcionario in object_list %}
              <tr>
                <td>{{ funcionario.id }}</td>
                <td><a href="{% url 'usuario:funcionario_detail' funcionario.pk %}">{{ funcionario.usuario.get_full_name }}</a></td>
                <td>{{ funcionario.telefone }}</td>
                <td>{{ funcionario.cri }}</td>
                <td>{% if funcionario.avatar %}<img src="{{ funcionario.avatar.url }}" alt="" width="50px">{% endif %}</td>
                <td>{{ funcionario.usuario.email }}</td>
                <td>{{ funcionario.get_tipo_display }}</td>
                <td width="120px">
                  <div class="botoes list">
                    <a href="{{ funcionario.get_absolute_url }}" class="btn btn-primary"><i class="icon-pencil"></i></a>
                    <a href="{{ funcionario.get_delete_url }}" class="btn btn-danger"><i class="icon-trash"></i></a>
                  </div>
                </td>
              </tr>
          </tbody>
          {% endfor %}
        </table>
        <!-- pagination -->
        {% include "includes/pagination.html" %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}