rimov/imovel/urls.py
from django.urls import path
from rimov.imovel import views as v


app_name = 'imovel'


urlpatterns = [
    path('', v.imovel_list, name='imovel_list'),
    path('add/', v.imovel_create, name='imovel_create'),
    path('<int:id>/', v.imovel_detail, name='imovel_detail'),
    path('<int:id>/update/', v.imovel_update, name='imovel_update'),
    path('<int:id>/delete/', v.imovel_delete, name='imovel_delete'),
    path('imagem/<int:id>/update/', v.imagem_update, name='imagem_update'),
]

rimov/urls.py
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path('', include('rimov.core.urls', namespace='core')),
    path('crm/', include('rimov.crm.urls', namespace='crm')),
    path('imovel/', include('rimov.imovel.urls', namespace='imovel')),
    path('usuario/', include('rimov.usuario.urls', namespace='usuario')),
    path('media/<path>/', serve, {'document_root = settings.MEDIA_ROOT'}),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rimov/imovel/models.py
from django.db import models
from django.urls import reverse_lazy
from rimov.usuario.models import Funcionario


STATUS = (
    ("D", "Disponível"),
    ("I", "Indisponível")

)
TIPO_PROPRIEDADE = (
    ("Apartamento", "Apartamento"),
    ("Casa", "Casa"),
    ("Casa Condomínio", "Casa Condomínio"),
    ("Casa Vila", "Casa Vila"),
    ("Cobertura", "Cobertura"),
    ("Comercial", "Comercial"),
    ("Fazenda", "Fazenda"),
    ("Flat", "Flat"),
    ("Kitnet", "Kitnet"),
    ("Loft", "Loft"),
    ("Sobrado", "Sobrado"),
    ("Terreno", "Terreno Padrão"),

)

CATEGORIA = (
    ("Alto Padrão", "Alto Padrão"),
    ("Médio Padrão", "Médio Padrão"),
    ("Baixo Padrão", "Baixo Padrão")

)

NEGOCIO = (
    ("Aluguel", "Aluguel"),
    ("Arrendamento", "Arrendamento"),
    ("Em Construção", "Em Construção"),
    ("Venda", "Venda")

)


class Imovel(models.Model):
    titulo = models.CharField(max_length=250)
    propriedade = models.TextField(choices=TIPO_PROPRIEDADE, blank=True, null=True)
    negocio = models.TextField(choices=NEGOCIO, blank=True, null=True)
    categoria = models.TextField(choices=CATEGORIA, blank=True, null=True)
    valor = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    localizacao = models.CharField(max_length=300, blank=True, null=True)
    endereco = models.CharField(max_length=300, blank=True, null=True)
    area = models.IntegerField(blank=True, null=True)
    num_quarto = models.IntegerField(blank=True, null=True)
    num_banheiro = models.IntegerField(blank=True, null=True)
    num_vaga = models.IntegerField(blank=True, null=True)
    descricao = models.TextField(unique=True, blank=True, null=True)
    corretor = models.ForeignKey(Funcionario, on_delete=models.CASCADE, blank=True, null=True)
    status = models.TextField(choices=STATUS)
    video = models.CharField(max_length=3000, blank=True, null=True)

    def imagens_url(self):
        if self.imagens and hasattr(self.imagens, 'url'):
            return self.imagens.url

    class Meta:
        ordering = ['-pk']
        verbose_name = "imóvel"
        verbose_name_plural = "imóveis"

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse_lazy('imovel:imovel_detail', kwargs={'id': self.id})

    def first_image(self):
        if self.imagem_imoveis:
            return self.imagem_imoveis.first()


class Galeria(models.Model):
    imovel = models.ForeignKey(Imovel, on_delete=models.CASCADE, related_name='imagem_imoveis', null=True)
    imagem = models.FileField('Imagem', upload_to='media', blank=False, null=True)

    class Meta:
        verbose_name = "Galeria do Imóvel"
        verbose_name_plural = "Galeria do Imóvel"

rimov/imovel/forms.py
from .models import Imovel
from django import forms


class ImovelForm(forms.ModelForm):

    class Meta:
        model = Imovel
        fields = '__all__'
        imagens = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

rimov/imovel/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ImovelForm
from .models import Imovel, Galeria


def imovel_list(request):
    imoveis = Imovel.objects.all()
    return render(request, 'imovel/imovel_list.html', {"imoveis": imoveis})


def imovel_create(request):
    form = ImovelForm(request.POST or None, request.FILES)
    if request.method == "POST":
        files = request.FILES.getlist('imagens')
        if form.is_valid():
            imovel = form.save()  # Pega a instância do Imovel.
            for file in files:
                Galeria.objects.create(imovel=imovel, imagem=file)
            return redirect('imovel:imovel_list')
    return render(request, 'imovel/imovel_form.html', {'form': form})


def imovel_detail(request, id):
    imovel = get_object_or_404(Imovel, pk=id)
    return render(request, 'imovel/imovel_detail.html', {'imovel': imovel})


def imovel_update(request, id):
    imovel = get_object_or_404(Imovel, pk=id)
    form = ImovelForm(instance=imovel)
    if request.method == 'POST':
        form = ImovelForm(request.POST, request.FILES, instance=imovel)

        if form.is_valid():
            imovel = form.save(commit=False)
            imovel.save()
            return redirect('imovel:imovel_list')

    context = {'form': form, 'imovel': imovel}
    return render(request, 'imovel/imovel_form.html', context)


def imovel_delete(request, id):
    imovel = Imovel.objects.get(id=id)
    imovel.delete()
    return redirect('imovel:imovel_list')


def imagem_update(request, id):
    galeria = Galeria.objects.get(id=id)
    if request.method == 'POST':
        imagem = request.FILES.get('imagem')
        galeria.imagem = imagem
        galeria.save()
    return redirect(galeria.imovel)

rimov/imovel/templates/imovel/imovel_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        {{ imovel.titulo }}
        <div class="btn-group float-right">
          <button class="btn btn-setting dropdown-toggle p-0" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="icon-settings"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </div>
        <a class="pull-right btn btn-sm btn-primary mr-2" style="color: white" href="{% url 'imovel:imovel_update' imovel.pk %}">
          <i class="fa fa-edit"></i> Editar
        </a>
        <span class="badge badge-success pull-right mr-2">Disponível</span>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-6">
            <img src="{{ imovel.first_image.imagem.url }}" width="200px">
          </div>
          <br>
          <div class="col-6">
            <h4><small><span class="text-muted">Propriedade:</span></small>
              {{ imovel.propriedade }}
            </h4>
            <h4><small><span class="text-muted">Negócio:</span></small>
              {{ imovel.negocio }}
            </h4>
            <h4><small><span class="text-muted">Categoria:</span></small>
              {{ imovel.categoria }}
            </h4>
            <h4><small><span class="text-muted">Valor:</span></small>
              {{ imovel.valor }}
            </h4>
          </div>
        </div>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <h4>Características</h4>
          <ul class="list-group list-group-flush">
            <li class="list-group-item no-border"><span class="text-muted">Área:</span> {{ imovel.area }}</li>
            <li class="list-group-item no-border"><span class="text-muted">Quartos:</span> {{ imovel.num_quarto }}</li>
            <li class="list-group-item no-border"><span class="text-muted">Banheiros:</span> {{ imovel.num_banheiro }}</li>
            <li class="list-group-item no-border"><span class="text-muted">Vagas:</span> {{ imovel.num_vaga }}</li>
          </ul>
        </li>
        <li class="list-group-item">
          <h4>Dados Gerais</h4>
          <ul class="list-group list-group-flush">
            <li class="list-group-item no-border"><span class="text-muted">Localização Aprox:</span> {{ imovel.localizacao }}</li>
            <li class="list-group-item no-border"><span class="text-muted">Endereço:</span> {{ imovel.endereco }}</li>
            <li class="list-group-item no-border"><span class="text-muted">Corretor:</span> {{ imovel.corretor.usuario.get_full_name }}</li>
          </ul>
        </li>
        <li class="list-group-item">
          <h4>Descrição</h4>
          <p class="text-justify">{{imovel.descricao}}</p>
        </li>
      </ul>
    </div>
  </div>
  <!-- <div class="col-lg-3">
    <div class="card">
      <div class="card-header">
        Contacts
        <span class="pull-right badge badge-success i-is-link" data-toggle="modal" data-target="#mymodal"><i class="fa fa-plus"></i> Add</span>
      </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item no-border">
            <span class="badge badge-warning">type</span> 11 98765-4321
            <span class="span-is-link pull-right" data-toggle="modal" data-target="#mymodal">
              <i class="fa fa-edit" style="margin-left: 10px;"></i>
            </span>
          </li>
        </ul>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        Title
        <span class="pull-right badge badge-success i-is-link" data-toggle="modal" data-target="#mymodal"><i class="fa fa-plus"></i> Add</span>
      </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <ul class="list-group list-group-flush">
              <li class="list-group-item no-border li-line pl-0 pr-0">
                <span class="text-muted">Label:</span> <span class="lead">text</span>
                <span class="span-is-link float-right" data-toggle="modal" data-target="#mymodal">
                  <i class="fa fa-edit" style="margin-left: 10px;"></i>
                </span>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div> -->
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        Video:
        <span class="pull-right badge badge-success i-is-link" data-toggle="modal" data-target="#mymodal"><i class="fa fa-plus"></i> Adicionar</span>
      </div>
      <div>
        <!-- card-body -->
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <ul class="list-group list-group-flush">
              <li class="list-group-item no-border li-line pl-0 pr-0">
                <span class="lead"><b>link:</b> {{imovel.video}}</span>
                <span class="span-is-link pull-right" data-toggle="modal" data-target="#mymodal">
                  <i class="fa fa-edit" style="margin-left: 10px;"></i>
                </span>
              </li>
              <span class="text-muted">Imagens:</span>
              <li class="list-group-item li-line pl-0 pr-0">
                <br>
                <div class="row">
                  {% for item in imovel.imagem_imoveis.all %}
                  <!-- {{ iterador.campo }} -->
                  {% if item.imagem %}
                  <div class="p-4">
                    <img src="{{ item.imagem.url }}" width="180">
                    <br>
                    <button 
                      class="btn btn-link editar" 
                      data-toggle="modal" 
                      data-target="#modalImagem"
                      data-id={{ item.id }}
                      data-url={% url 'imovel:imagem_update' item.id %}
                    >Editar</button>
                  </div>
                  {% endif %}
                  {% endfor %}
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!-- Modal -->
{% include "./includes/modal_foto.html" %}
{% endblock content %}

{% block js %}
  <script>
    $('.editar').on('click', function(){
      $('#id').val($(this).data('id'));
      $('#formImagem').attr('action', $(this).data('url'));
    });
  </script>
{% endblock js %}

rimov/imovel/templates/imovel/imovel_form.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block css %}
<style>
  input, textarea {
    text-transform: uppercase;
  }
  span.required:after {
    content: "*";
    color: red;
  }
</style>
{% endblock css %}
{% block content %}
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header">
        <strong>Imóvel</strong>
        <!-- <small>Form</small> -->
      </div>
      <div class="card-body">
        <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error {% endif %}">
            <label for="{{ field.id_for_label }}">
              {% if field.field.required %}
              <span class="required">{{ field.label }} </span>
              {% else %}
              {{ field.label }}
              {% endif %}
            </label>
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
            <span class="text-muted">{{ error }}</span>
            {% endfor %}
          </div>
          {% endfor %}
          <label for="imagens">Imagens:</label> <input type="file" name="imagens" multiple="">
          <br>
          <input type="button" value="Voltar" class="btn btn-info" onClick="history.go(-1)"> <input type="submit" class="btn btn-success" value="Salvar">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

rimov/imovel/templates/imovel/imovel_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

  {% for message in messages %}
    {% if 'success' in message.tags %}
    <p class="alert alert-success" role="alert"><span style="font-weight:bold">{{ message }}</span></p>
    {% elif 'warning' in message.tags %}
    <p class="alert alert-warning" role="alert"><span style="font-weight:bold">{{ message }}</span></p>
    {% endif %}
  {% endfor %}

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Imóveis
        <span class="float-right">1 of 10 resultados (100 total)</span>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-md-auto">
            <a class="btn btn-primary" href="{% url 'imovel:imovel_create' %}">
              <i class="fa fa-plus"></i>
              Adicionar
            </a>
          </div>
          <div class="col">
            <form action="." method="GET">
              <div class="row">
                <div class="col p-ari-5">
                  <input name="search" class="form-control mb-2" type="text" placeholder="Busca..." />
                </div>
                <div class="col-auto">
                  <button class="btn btn-success mb-2" type="submit">OK</button>
                  <button class="btn btn-link mb-2">Limpar</button>
                </div>
              </div>
            </form>
          </div>
        </div>
        <!-- TABLE -->
        <table class="table table-responsive-sm table-hover table-striped">
          <thead>
            <tr>
              <th>NOME</th>
              <th>NEGÓCIO</th>
              <th>CATEGORIA</th>
              <th>PROPRIEDADE</th>
              <th class="text-center">STATUS</th>
              <th>CORRETOR</th>
              <th>LOCALIZAÇÃO</th>
              <th>IMAGEM</th>
              <th class="text-center">AÇÕES</th>
            </tr>
          </thead>
          <tbody>
            {% for imovel in imoveis %}
              <tr>
                <td>
                  <a href="{% url 'imovel:imovel_detail' imovel.pk %}">{{ imovel.titulo }}</a>
                </td>
                <td>{{ imovel.negocio }}</td>
                <td>{{ imovel.categoria }}</td>
                <td>{{ imovel.propriedade }}</td>
                <td class="text-center">
                  {% if imovel.status == 'D' %}
                    <span class="badge badge-success">Disponível</span>
                  {% else %}
                    <span class="badge badge-danger">Indisponível</span>
                  {% endif %}
                </td>
                <td>{{ imovel.corretor.usuario.get_full_name }}</td>
                <td>{{ imovel.localizacao }}</td>
                <td>
                  <img src="{{ imovel.first_image.imagem.url }}" alt="" height="80px">
                </td>
                <td width="120px">
                  <div class="botoes list">
                    <a href="{% url 'imovel:imovel_update' imovel.pk %}" class="btn btn-primary"><i class="icon-pencil"></i></a>
                    <span data-url="{% url 'imovel:imovel_delete' imovel.pk %}" class="btn btn-danger delete"><i class="icon-trash"></i></span>
                  </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <!-- pagination -->
        {% include "includes/pagination.html" %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block js %}
  <script>
    $('.delete').click(function() {
      const url = $(this).data("url");
      Swal.fire({
        title: 'Deseja deletar este item?',
        showCancelButton: true,
        confirmButtonText: `Sim`,
      }).then((result) => {
        /* Read more about isConfirmed, isDenied below */
        if (result.isConfirmed) {
          // Swal.fire('Saved!', '', 'success')
          window.location.href = url
        }
      })
    });

    window.setTimeout(function() {
      $(".alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove();
      });
    }, 3000);
  </script>
{% endblock js %}