rimov/core/urls.py
from django.urls import path
from rimov.core import views as v


app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
    path('painel/', v.painel, name='painel'),
    path('team/', v.team, name='team'),
    path('pgrid/', v.pgrid, name='pgrid'),
    path('pgrid/<int:id>/', v.psingle, name='psingle'),
    path('contact/', v.contact, name='contact'),
]

rimov/crm/urls.py
from django.urls import include, path
from rimov.crm import views as v


app_name = 'crm'


pf_urlpatterns = [
    path('', v.pf_list, name='pf_list'),
    path('add/', v.PFCreate.as_view(), name='pf_create'),
    # path('<int:pk>/', v.pf_detail, name='pf_detail'),
    path('<int:pk>/update/', v.PFUpdate.as_view(), name='pf_update'),
    path('<int:pk>/delete/', v.pf_delete, name='pf_delete'),
]

pj_urlpatterns = [
    path('', v.pj_list, name='pj_list'),
    path('add/', v.PJCreate.as_view(), name='pj_create'),
    # path('<int:pk>/', v.pj_detail, name='pj_detail'),
    path('<int:pk>/update/', v.PJUpdate.as_view(), name='pj_update'),
    path('<int:pk>/delete/', v.pj_delete, name='pj_delete'),
]


urlpatterns = [
    path('pessoa-fisica/', include(pf_urlpatterns)),
    path('pessoa-juridica/', include(pj_urlpatterns)),
]

rimov/imovel/urls.py
from django.urls import path
from rimov.imovel import views as v


app_name = 'imovel'


urlpatterns = [
    path('', v.imovel_list, name='imovel_list'),
    path('add/', v.imovel_create, name='imovel_create'),
    path('<int:id>/', v.imovel_detail, name='imovel_detail'),
    path('<int:id>/update/', v.imovel_update, name='imovel_update'),
    path('<int:id>/delete/', v.imovel_delete, name='imovel_delete'),
    path('imagem/<int:id>/update/', v.imagem_update, name='imagem_update'),
]

rimov/urls.py
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path('', include('rimov.core.urls', namespace='core')),
    path('crm/', include('rimov.crm.urls', namespace='crm')),
    path('imovel/', include('rimov.imovel.urls', namespace='imovel')),
    path('usuario/', include('rimov.usuario.urls', namespace='usuario')),
    path('media/<path>/', serve, {'document_root = settings.MEDIA_ROOT'}),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rimov/usuario/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from rimov.usuario import views as v
from rimov.usuario.forms import LoginForm


app_name = 'usuario'


urlpatterns = [
    path('', v.FuncionarioListView.as_view(), name='funcionario_list'),
    path('login/', LoginView.as_view(form_class=LoginForm), name='login'),
    path(
        'logout/',
        LogoutView.as_view(),
        # {'next_page': settings.LOGOUT_REDIRECT_URL},
        name='logout'
    ),
    path('add/', v.funcionario_create, name='funcionario_create'),
    path('<int:id>/', v.funcionario_detail, name='funcionario_detail'),
    path('<int:pk>/update/', v.FuncionarioUpdateView.as_view(), name='funcionario_update'),
    path('<int:pk>/delete/', v.FuncionarioDeleteView.as_view(), name='funcionario_delete'),
]

rimov/core/models.py
from django.db import models
from localflavor.br.br_states import STATE_CHOICES


class Cidade(models.Model):
    nome = models.CharField('cidade', max_length=100, unique=True)
    uf = models.CharField('UF', max_length=2, choices=STATE_CHOICES, blank=True)

    def __str__(self):
        return self.nome

    class Meta:
        ordering = ('nome',)
        verbose_name = 'cidade'
        verbose_name_plural = 'cidades'


class Endereco(models.Model):
    endereco = models.CharField(
        'endereço',
        max_length=100,
        null=True,
        blank=True
    )
    numero = models.IntegerField('número', null=True, blank=True)
    complemento = models.CharField(
        'complemento',
        max_length=100,
        null=True,
        blank=True
    )
    bairro = models.CharField(
        'bairro',
        max_length=100,
        null=True,
        blank=True
    )
    cidade = models.ForeignKey(
        Cidade,
        verbose_name='cidade',
        on_delete=models.CASCADE,
    )
    cep = models.CharField('CEP', max_length=9, null=True, blank=True)

    class Meta:
        abstract = True

rimov/core/views.py
from django.shortcuts import render, get_object_or_404
from rimov.imovel.models import Imovel
from rimov.usuario.models import Funcionario


def index(request):
    template_name = 'index.html'
    imoveis = Imovel.objects.all()
    context = {'imoveis': imoveis}
    return render(request, template_name, context)


def painel(request):
    template_name = 'painel.html'
    return render(request, template_name)


def team(request):
    template_name = 'team.html'
    funcionarios = Funcionario.objects.all()
    context = {'funcionarios': funcionarios}
    return render(request, template_name, context)


def pgrid(request):
    template_name = 'property_grid.html'
    imoveis = Imovel.objects.all()
    context = {'imoveis': imoveis}
    return render(request, template_name, context)


def psingle(request, id):
    imovel = get_object_or_404(Imovel, pk=id)
    context = {'imovel': imovel}
    return render(request, 'property_single.html', context)


def contact(request):
    template_name = 'contact.html'
    return render(request, template_name)

rimov/core/templates/includes/breadcrumb.html
<!-- Breadcrumb-->
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="{% url 'core:index' %}">Home</a>
  </li>
  <li class="breadcrumb-item">
    <a href=".">List</a>
  </li>
  <li class="breadcrumb-item active">Painel Administrativo</li>
  <!-- Breadcrumb Menu-->
  <li class="breadcrumb-menu d-md-down-none">
    <div class="btn-group" role="group" aria-label="Button group">
      <!--<a class="btn" href="">
        <i class="icon-speech"></i>-->
      </a>
      <a class="btn" href="{% url 'core:index' %}">
        <i class="icon-home"></i>  Site</a>
      <!--<a class="btn" href="">
        <i class="icon-settings"></i>  Settings</a>-->
    </div>
  </li>
  {% block breadcrumb %}{% endblock breadcrumb %}
</ol>

rimov/core/templates/includes/footer.html
<footer class="app-footer">
  <div>
    <a href="">Ronaldo Santos Imóveis</a>
    <span>&copy; 2021</span>
  </div>
</footer>

rimov/core/templates/includes/modal.html
<div class="modal fade" id="mymodal" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Title</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <form action="." method="POST">
        <div class="modal-body">
          <label for="firstname">Name</label>
          <input id="firstname" name="firstname" class="form-control" type="text" placeholder="Name" />
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
      </form>
    </div>
  </div>
</div>

rimov/core/templates/includes/navbar.html
{% load static %}
<header class="app-header navbar">
  <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{% url 'core:index' %}">
    <!--<img class="navbar-brand-full" src="{% static 'img/brand/logo.svg' %}" width="89" height="25" alt="CoreUI Logo">
    <img class="navbar-brand-minimized" src="{% static 'img/brand/sygnet.svg' %}" width="30" height="30" alt="CoreUI Logo">-->
  </a>
  <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
    <span class="navbar-toggler-icon"></span>
  </button>
  <ul class="nav navbar-nav d-md-down-none">
    <li class="nav-item px-3">
      <a class="nav-link" href="{ url 'core:painel' %}">Painel</a>
    </li>
    <!--<li class="nav-item px-3">
      <a class="nav-link" href="#">Users</a>
    </li>
    <li class="nav-item px-3">
      <a class="nav-link" href="#">Settings</a>
    </li>-->
  </ul>
  <ul class="nav navbar-nav ml-auto">
    <li class="nav-item dropdown d-md-down-none">
      <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="icon-bell"></i>
        <span class="badge badge-pill badge-danger">5</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg">
        <div class="dropdown-header text-center">
          <strong>You have 5 notifications</strong>
        </div>
        <a class="dropdown-item" href="#">
          <i class="icon-user-follow text-success"></i> New user registered</a>
        <a class="dropdown-item" href="#">
          <i class="icon-user-unfollow text-danger"></i> User deleted</a>
        <a class="dropdown-item" href="#">
          <i class="icon-chart text-info"></i> Sales report is ready</a>
        <a class="dropdown-item" href="#">
          <i class="icon-basket-loaded text-primary"></i> New client</a>
        <a class="dropdown-item" href="#">
          <i class="icon-speedometer text-warning"></i> Server overloaded</a>
        <div class="dropdown-header text-center">
          <strong>Server</strong>
        </div>
        <a class="dropdown-item" href="#">
          <div class="text-uppercase mb-1">
            <small>
              <b>CPU Usage</b>
            </small>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-info" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
          <small class="text-muted">348 Processes. 1/4 Cores.</small>
        </a>
        <a class="dropdown-item" href="#">
          <div class="text-uppercase mb-1">
            <small>
              <b>Memory Usage</b>
            </small>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-warning" role="progressbar" style="width: 70%" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
          <small class="text-muted">11444GB/16384MB</small>
        </a>
        <a class="dropdown-item" href="#">
          <div class="text-uppercase mb-1">
            <small>
              <b>SSD 1 Usage</b>
            </small>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-danger" role="progressbar" style="width: 95%" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
          <small class="text-muted">243GB/256GB</small>
        </a>
      </div>
    </li>
    <li class="nav-item dropdown d-md-down-none">
      <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="icon-list"></i>
        <span class="badge badge-pill badge-warning">15</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg">
        <div class="dropdown-header text-center">
          <strong>You have 5 pending tasks</strong>
        </div>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">Upgrade NPM &amp; Bower
            <span class="float-right">
              <strong>0%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-info" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">ReactJS Version
            <span class="float-right">
              <strong>25%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-danger" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">VueJS Version
            <span class="float-right">
              <strong>50%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-warning" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">Add new layouts
            <span class="float-right">
              <strong>75%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-info" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">Angular 2 Cli Version
            <span class="float-right">
              <strong>100%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-success" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item text-center" href="#">
          <strong>View all tasks</strong>
        </a>
      </div>
    </li>
    <li class="nav-item dropdown d-md-down-none">
      <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="icon-envelope-letter"></i>
        <span class="badge badge-pill badge-info">7</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg">
        <div class="dropdown-header text-center">
          <strong>You have 4 messages</strong>
        </div>
        <a class="dropdown-item" href="#">
          <div class="message">
            <div class="py-3 mr-3 float-left">
              <div class="avatar">
                <img class="img-avatar" src="{% static 'img/avatars/7.jpg' %}" alt="admin@bootstrapmaster.com">
                <span class="avatar-status badge-success"></span>
              </div>
            </div>
            <div>
              <small class="text-muted">John Doe</small>
              <small class="text-muted float-right mt-1">Just now</small>
            </div>
            <div class="text-truncate font-weight-bold">
              <span class="fa fa-exclamation text-danger"></span> Important message</div>
            <div class="small text-muted text-truncate">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</div>
          </div>
        </a>
        <a class="dropdown-item" href="#">
          <div class="message">
            <div class="py-3 mr-3 float-left">
              <div class="avatar">
                <img class="img-avatar" src="{% static 'img/avatars/6.jpg' %}" alt="admin@bootstrapmaster.com">
                <span class="avatar-status badge-warning"></span>
              </div>
            </div>
            <div>
              <small class="text-muted">John Doe</small>
              <small class="text-muted float-right mt-1">5 minutes ago</small>
            </div>
            <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
            <div class="small text-muted text-truncate">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</div>
          </div>
        </a>
        <a class="dropdown-item" href="#">
          <div class="message">
            <div class="py-3 mr-3 float-left">
              <div class="avatar">
                <img class="img-avatar" src="{% static 'img/avatars/5.jpg' %}" alt="admin@bootstrapmaster.com">
                <span class="avatar-status badge-danger"></span>
              </div>
            </div>
            <div>
              <small class="text-muted">John Doe</small>
              <small class="text-muted float-right mt-1">1:52 PM</small>
            </div>
            <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
            <div class="small text-muted text-truncate">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</div>
          </div>
        </a>
        <a class="dropdown-item" href="#">
          <div class="message">
            <div class="py-3 mr-3 float-left">
              <div class="avatar">
                <img class="img-avatar" src="{% static 'img/avatars/4.jpg' %}" alt="admin@bootstrapmaster.com">
                <span class="avatar-status badge-info"></span>
              </div>
            </div>
            <div>
              <small class="text-muted">John Doe</small>
              <small class="text-muted float-right mt-1">4:03 PM</small>
            </div>
            <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
            <div class="small text-muted text-truncate">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</div>
          </div>
        </a>
        <a class="dropdown-item text-center" href="#">
          <strong>View all messages</strong>
        </a>
      </div>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <img class="img-avatar" src="{% static 'img/avatars/6.jpg' %}" alt="avatar">
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <div class="dropdown-header text-center">
          <strong>Account</strong>
        </div>
        <a class="dropdown-item" href="#">
          <i class="fa fa-bell-o"></i> Updates
          <span class="badge badge-info">42</span>
        </a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-envelope-o"></i> Messages
          <span class="badge badge-success">42</span>
        </a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-tasks"></i> Tasks
          <span class="badge badge-danger">42</span>
        </a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-comments"></i> Comments
          <span class="badge badge-warning">42</span>
        </a>
        <div class="dropdown-header text-center">
          <strong>Settings</strong>
        </div>
        <a class="dropdown-item" href="#">
          <i class="fa fa-user"></i> Profile</a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-wrench"></i> Settings</a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-usd"></i> Payments
          <span class="badge badge-secondary">42</span>
        </a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-file"></i> Projects
          <span class="badge badge-primary">42</span>
        </a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">
          <i class="fa fa-shield"></i> Lock Account</a>
        <a class="dropdown-item" href="{% url 'usuario:logout' %}">
          <i class="fa fa-lock"></i> Logout</a>
      </div>
    </li>
  </ul>
  <button class="navbar-toggler aside-menu-toggler d-md-down-none" type="button" data-toggle="aside-menu-lg-show">
    <span class="navbar-toggler-icon"></span>
  </button>
  <button class="navbar-toggler aside-menu-toggler d-lg-none" type="button" data-toggle="aside-menu-show">
    <span class="navbar-toggler-icon"></span>
  </button>
</header>

rimov/core/templates/includes/pagination.html
<!-- https://gist.github.com/rg3915/01ca76f099f431c24bc0536bef83076b -->
<!-- Use https://gist.github.com/rg3915/01ca76f099f431c24bc0536bef83076b#file-pagination02-html -->
<div class="row text-center">
  <div class="col-lg-12">
    <ul class="pagination">
      <li class="page-item"><a class="page-link" href="">&laquo;</a></li>
      <li class="page-item"><a class="page-link" href="">1</a></li>
      <li class="page-item"><a class="page-link" href="">2</a></li>
      <li class="page-item"><a class="page-link" href="">...</a></li>
      <li class="page-item"><a class="page-link" href="">4</a></li>
      <li class="page-item"><a class="page-link" href="">5</a></li>
      <li class="page-item active"><a class="page-link" href="">6</a></li>
      <li class="page-item"><a class="page-link" href="">7</a></li>
      <li class="page-item"><a class="page-link" href="">8</a></li>
      <li class="page-item"><a class="page-link" href="">...</a></li>
      <li class="page-item"><a class="page-link" href="">10</a></li>
      <li class="page-item"><a class="page-link" href="">11</a></li>
      <li class="page-item"><a class="page-link" href="">&raquo;</a></li>

      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo;</a></li>
      {% endif %}

      {% for pg in page_obj.paginator.page_range %}
        <!-- Sempre mostra as 3 primeiras e 3 últimas páginas -->
          {% if pg == 1 or pg == 2 or pg == 3 or pg == page_obj.paginator.num_pages or pg == page_obj.paginator.num_pages|add:'-1' or pg == page_obj.paginator.num_pages|add:'-2' %}
            {% if page_obj.number == pg %}
              <li class="active"><a class="page-link" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
            {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
            {% endif %}

          {% else %}

            {% if page_obj.number == pg %}
              <li class="active"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
            {% elif pg > page_obj.number|add:'-4' and pg < page_obj.number|add:'4' %} <!-- Mostra 3 páginas antes e 3 páginas depois da atual -->
              <li class="page-item"><a class="page-link" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
            {% elif pg == page_obj.number|add:'-4' or pg == page_obj.number|add:'4' %}
              <li class="page-item"><a class="page-link" href="">...</a></li>
            {% endif %}
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&q={{ request.GET.q }}">&raquo;</a></li>
        {% endif %}
    </ul>
  </div>
</div>

rimov/core/templates/includes/sidebar.html
{% load static %}
<div class="sidebar">
  <nav class="sidebar-nav">
    <ul class="nav">
      <li class="nav-item">
        <!--<a class="nav-link" href="{% url 'core:painel' %}">
          <i class="nav-icon icon-speedometer"></i> Dashboard
          <!-- <span class="badge badge-primary">NEW</span>
        </a>-->
        <br>
        <p><a href=""><img src="{% static 'img/logoRS.jpg' %}" width="190"></a></p>
        <br>
      </li>
      <li class="nav-title">Imóveis</li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'imovel:imovel_list' %}">
          <i class="nav-icon icon-home"></i> Imóveis</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'imovel:imovel_create' %}">
          <i class="nav-icon icon-plus"></i> Cadastrar</a>
      </li>
      <li class="nav-title">Funcionários</li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'usuario:funcionario_list' %}">
          <i class="nav-icon icon-people"></i> Funcionários</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'usuario:funcionario_create' %}">
          <i class="nav-icon icon-plus"></i> Cadastrar</a>
      </li>
      <li class="nav-title">Clientes</li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'crm:pf_list' %}">
          <i class="nav-icon icon-people"></i> Pessoa Física</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'crm:pj_list' %}">
          <i class="nav-icon icon-people"></i> Pessoa Jurídica</a>
      </li>
    </ul>
  </nav>
  <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>